#include "doctest/doctest.h"

#include "machines/CFG.h"
#include "parser/lr.h"

class LRTest {
protected:
    LR lr{};

protected:
    LR::ItemSet closure(const LR::ItemSet& item, const std::string& separator, const CFG& cfg) {
        return LR::closure(item, separator, cfg);
    }

    void setup(const CFG& cfg) { this->lr = LR(cfg); }

    const LR::ParsingTable& get_table() const { return this->lr.table; }
};

TEST_SUITE("LRTests") {
    TEST_CASE_FIXTURE(LRTest, "[LRTests] closure") {
        const std::string separator("·");
        const LR::ItemSet start_item_set{{LR::Item{"S", {separator, "A", "A"}}}};

        const CFG cfg("./test/res/input/CFG2.json");

        CHECK_EQ(closure(start_item_set, separator, cfg),
                 LR::ItemSet{{{"A", {"·", "a", "A"}}, {"A", {"·", "b"}}, {"S", {"·", "A", "A"}}}});
    }

    TEST_CASE_FIXTURE(LRTest, "[LRTests] parsing_table") {
        const CFG cfg("./test/res/input/CFG2.json");
        setup(cfg);

        LR::ParsingTable table{
            {0, {{{"a", {LR::ActionType::Shift, 1}}, {"b", {LR::ActionType::Shift, 2}}}, {{"A", 3}, {"S", 4}}}},
            {1, {{{"a", {LR::ActionType::Shift, 1}}, {"b", {LR::ActionType::Shift, 2}}}, {{"A", 5}}}},
            {2,
             {{{"$", {LR::ActionType::Reduce, 1}},
               {"a", {LR::ActionType::Reduce, 1}},
               {"b", {LR::ActionType::Reduce, 1}}},
              {}}},
            {3, {{{"a", {LR::ActionType::Shift, 1}}, {"b", {LR::ActionType::Shift, 2}}}, {{"A", 6}}}},
            {4, {{{"$", {LR::ActionType::Accept, 0}}}, {}}},
            {5,
             {{{"$", {LR::ActionType::Reduce, 0}},
               {"a", {LR::ActionType::Reduce, 0}},
               {"b", {LR::ActionType::Reduce, 0}}},
              {}}},
            {6, {{{"$", {LR::ActionType::Reduce, 2}}}, {}}}};

        CHECK_EQ(table, get_table());
    }

    TEST_CASE_FIXTURE(LRTest, "[LRTests] table_edge_case_0") {
        const CFG cfg = CFG::parse_ebnf("test/res/input/EBNF0.txt");
        setup(cfg);

        const LR::ParsingTable table{
            {0, {{{"literal", {LR::ActionType::Shift, 3}}}, {{"<assignment>", 4}, {"<expression>", 1}, {"<term>", 2}}}},
            {1, {{{";", {LR::ActionType::Shift, 5}}}, {}}},
            {2,
             {{{"$", {LR::ActionType::Reduce, 1}},
               {"+", {LR::ActionType::Shift, 6}},
               {";", {LR::ActionType::Reduce, 1}}},
              {}}},
            {3,
             {{{"$", {LR::ActionType::Reduce, 3}},
               {"*", {LR::ActionType::Shift, 7}},
               {"+", {LR::ActionType::Reduce, 3}},
               {";", {LR::ActionType::Reduce, 3}}},
              {}}},
            {4, {{{"$", {LR::ActionType::Accept, 0}}}, {}}},
            {5, {{{"$", {LR::ActionType::Reduce, 0}}}, {}}},
            {6, {{{"literal", {LR::ActionType::Shift, 3}}}, {{"<expression>", 8}, {"<term>", 2}}}},
            {7, {{{"literal", {LR::ActionType::Shift, 3}}}, {{"<term>", 9}}}},
            {8, {{{"$", {LR::ActionType::Reduce, 2}}, {";", {LR::ActionType::Reduce, 2}}}, {}}},
            {9,
             {{{"$", {LR::ActionType::Reduce, 4}},
               {"+", {LR::ActionType::Reduce, 4}},
               {";", {LR::ActionType::Reduce, 4}}},
              {}}}};

        CHECK_EQ(table, get_table());
    }

    TEST_CASE_FIXTURE(LRTest, "[LRTests] bro_parse_table") {
        const CFG cfg = CFG::parse_ebnf("test/res/input/EBNF2CFG.txt");
        setup(cfg);

        const LR::ParsingTable table{
            {0, {{{"fn", {LR::ActionType::Shift, 1}}}, {{"<function>", 2}, {"<program>", 3}}}},
            {1, {{{"identifier", {LR::ActionType::Shift, 4}}}, {}}},
            {2,
             {{{"$", {LR::ActionType::Reduce, 27}}, {"fn", {LR::ActionType::Shift, 1}}},
              {{"<function>", 2}, {"<program>", 5}}}},
            {3, {{{"$", {LR::ActionType::Accept, 0}}}, {}}},
            {4, {{{"(", {LR::ActionType::Shift, 6}}}, {}}},
            {5, {{{"$", {LR::ActionType::Reduce, 28}}}, {}}},
            {6,
             {{{")", {LR::ActionType::Shift, 8}}, {"identifier", {LR::ActionType::Shift, 7}}}, {{"<arguments>", 9}}}},
            {7,
             {{{"$", {LR::ActionType::Reduce, 0}},
               {")", {LR::ActionType::Reduce, 0}},
               {",", {LR::ActionType::Shift, 10}}},
              {}}},
            {8, {{{"{", {LR::ActionType::Shift, 11}}}, {}}},
            {9, {{{")", {LR::ActionType::Shift, 12}}}, {}}},
            {10, {{{"identifier", {LR::ActionType::Shift, 7}}}, {{"<arguments>", 13}}}},
            {11,
             {{{"identifier", {LR::ActionType::Shift, 14}},
               {"if", {LR::ActionType::Shift, 18}},
               {"let", {LR::ActionType::Shift, 15}},
               {"return", {LR::ActionType::Shift, 19}}},
              {{"<assignment>", 20},
               {"<body>", 17},
               {"<function_call>", 21},
               {"<if>", 22},
               {"<return>", 23},
               {"<statement>", 16}}}},
            {12, {{{"{", {LR::ActionType::Shift, 24}}}, {}}},
            {13, {{{"$", {LR::ActionType::Reduce, 1}}, {")", {LR::ActionType::Reduce, 1}}}, {}}},
            {14, {{{"(", {LR::ActionType::Shift, 26}}, {"=", {LR::ActionType::Shift, 25}}}, {}}},
            {15, {{{"identifier", {LR::ActionType::Shift, 27}}}, {}}},
            {16,
             {{{"$", {LR::ActionType::Reduce, 4}},
               {"identifier", {LR::ActionType::Shift, 14}},
               {"if", {LR::ActionType::Shift, 18}},
               {"let", {LR::ActionType::Shift, 15}},
               {"return", {LR::ActionType::Shift, 19}},
               {"}", {LR::ActionType::Reduce, 4}}},
              {{"<assignment>", 20},
               {"<body>", 28},
               {"<function_call>", 21},
               {"<if>", 22},
               {"<return>", 23},
               {"<statement>", 16}}}},
            {17, {{{"}", {LR::ActionType::Shift, 29}}}, {}}},
            {18,
             {{{"!", {LR::ActionType::Shift, 31}},
               {"(", {LR::ActionType::Shift, 32}},
               {"identifier", {LR::ActionType::Shift, 33}},
               {"literal", {LR::ActionType::Shift, 34}}},
              {{"<expression>", 35}, {"<factor>", 36}, {"<term>", 30}}}},
            {19,
             {{{"!", {LR::ActionType::Shift, 31}},
               {"(", {LR::ActionType::Shift, 32}},
               {"identifier", {LR::ActionType::Shift, 33}},
               {"literal", {LR::ActionType::Shift, 34}}},
              {{"<expression>", 37}, {"<factor>", 36}, {"<term>", 30}}}},
            {20, {{{"$", {LR::ActionType::Reduce, 30}}, {"}", {LR::ActionType::Reduce, 30}}}, {}}},
            {21, {{{"$", {LR::ActionType::Reduce, 31}}, {"}", {LR::ActionType::Reduce, 31}}}, {}}},
            {22, {{{"$", {LR::ActionType::Reduce, 32}}, {"}", {LR::ActionType::Reduce, 32}}}, {}}},
            {23, {{{"$", {LR::ActionType::Reduce, 33}}, {"}", {LR::ActionType::Reduce, 33}}}, {}}},
            {24,
             {{{"identifier", {LR::ActionType::Shift, 14}},
               {"if", {LR::ActionType::Shift, 18}},
               {"let", {LR::ActionType::Shift, 15}},
               {"return", {LR::ActionType::Shift, 19}}},
              {{"<assignment>", 20},
               {"<body>", 38},
               {"<function_call>", 21},
               {"<if>", 22},
               {"<return>", 23},
               {"<statement>", 16}}}},
            {25,
             {{{"!", {LR::ActionType::Shift, 31}},
               {"(", {LR::ActionType::Shift, 32}},
               {"identifier", {LR::ActionType::Shift, 33}},
               {"literal", {LR::ActionType::Shift, 34}}},
              {{"<expression>", 39}, {"<factor>", 36}, {"<term>", 30}}}},
            {26,
             {{{"!", {LR::ActionType::Shift, 31}},
               {"(", {LR::ActionType::Shift, 32}},
               {")", {LR::ActionType::Shift, 41}},
               {"identifier", {LR::ActionType::Shift, 33}},
               {"literal", {LR::ActionType::Shift, 34}}},
              {{"<call_arguments>", 42}, {"<expression>", 40}, {"<factor>", 36}, {"<term>", 30}}}},
            {27, {{{"=", {LR::ActionType::Shift, 43}}}, {}}},
            {28, {{{"$", {LR::ActionType::Reduce, 5}}, {"}", {LR::ActionType::Reduce, 5}}}, {}}},
            {29, {{{"$", {LR::ActionType::Reduce, 21}}}, {}}},
            {30,
             {{{"!", {LR::ActionType::Reduce, 8}},
               {"$", {LR::ActionType::Reduce, 8}},
               {")", {LR::ActionType::Reduce, 8}},
               {"*", {LR::ActionType::Reduce, 8}},
               {"+", {LR::ActionType::Reduce, 8}},
               {",", {LR::ActionType::Reduce, 8}},
               {"-", {LR::ActionType::Reduce, 8}},
               {"/", {LR::ActionType::Reduce, 8}},
               {";", {LR::ActionType::Reduce, 8}},
               {"<", {LR::ActionType::Reduce, 8}},
               {"=", {LR::ActionType::Reduce, 8}},
               {">", {LR::ActionType::Reduce, 8}},
               {"{", {LR::ActionType::Reduce, 8}}},
              {}}},
            {31,
             {{{"!", {LR::ActionType::Shift, 31}},
               {"(", {LR::ActionType::Shift, 32}},
               {"identifier", {LR::ActionType::Shift, 33}},
               {"literal", {LR::ActionType::Shift, 34}}},
              {{"<expression>", 50}, {"<factor>", 36}, {"<term>", 30}}}},
            {32,
             {{{"!", {LR::ActionType::Shift, 31}},
               {"(", {LR::ActionType::Shift, 32}},
               {"identifier", {LR::ActionType::Shift, 33}},
               {"literal", {LR::ActionType::Shift, 34}}},
              {{"<expression>", 51}, {"<factor>", 36}, {"<term>", 30}}}},
            {33,
             {{{"!", {LR::ActionType::Reduce, 19}},
               {"$", {LR::ActionType::Reduce, 19}},
               {")", {LR::ActionType::Reduce, 19}},
               {"*", {LR::ActionType::Reduce, 19}},
               {"+", {LR::ActionType::Reduce, 19}},
               {",", {LR::ActionType::Reduce, 19}},
               {"-", {LR::ActionType::Reduce, 19}},
               {"/", {LR::ActionType::Reduce, 19}},
               {";", {LR::ActionType::Reduce, 19}},
               {"<", {LR::ActionType::Reduce, 19}},
               {"=", {LR::ActionType::Reduce, 19}},
               {">", {LR::ActionType::Reduce, 19}},
               {"{", {LR::ActionType::Reduce, 19}}},
              {}}},
            {34,
             {{{"!", {LR::ActionType::Reduce, 20}},
               {"$", {LR::ActionType::Reduce, 20}},
               {")", {LR::ActionType::Reduce, 20}},
               {"*", {LR::ActionType::Reduce, 20}},
               {"+", {LR::ActionType::Reduce, 20}},
               {",", {LR::ActionType::Reduce, 20}},
               {"-", {LR::ActionType::Reduce, 20}},
               {"/", {LR::ActionType::Reduce, 20}},
               {";", {LR::ActionType::Reduce, 20}},
               {"<", {LR::ActionType::Reduce, 20}},
               {"=", {LR::ActionType::Reduce, 20}},
               {">", {LR::ActionType::Reduce, 20}},
               {"{", {LR::ActionType::Reduce, 20}}},
              {}}},
            {35, {{{"{", {LR::ActionType::Shift, 52}}}, {}}},
            {36,
             {{{"!", {LR::ActionType::Reduce, 34}},
               {"$", {LR::ActionType::Reduce, 34}},
               {")", {LR::ActionType::Reduce, 34}},
               {"*", {LR::ActionType::Reduce, 34}},
               {"+", {LR::ActionType::Reduce, 34}},
               {",", {LR::ActionType::Reduce, 34}},
               {"-", {LR::ActionType::Reduce, 34}},
               {"/", {LR::ActionType::Reduce, 34}},
               {";", {LR::ActionType::Reduce, 34}},
               {"<", {LR::ActionType::Reduce, 34}},
               {"=", {LR::ActionType::Reduce, 34}},
               {">", {LR::ActionType::Reduce, 34}},
               {"{", {LR::ActionType::Reduce, 34}}},
              {}}},
            {37, {{{";", {LR::ActionType::Shift, 55}}}, {}}},
            {38, {{{"}", {LR::ActionType::Shift, 56}}}, {}}},
            {39, {{{";", {LR::ActionType::Shift, 57}}}, {}}},
            {40,
             {{{"$", {LR::ActionType::Reduce, 6}},
               {")", {LR::ActionType::Reduce, 6}},
               {",", {LR::ActionType::Shift, 58}}},
              {}}},
            {41, {{{";", {LR::ActionType::Shift, 59}}}, {}}},
            {42, {{{")", {LR::ActionType::Shift, 60}}}, {}}},
            {43,
             {{{"!", {LR::ActionType::Shift, 31}},
               {"(", {LR::ActionType::Shift, 32}},
               {"identifier", {LR::ActionType::Shift, 33}},
               {"literal", {LR::ActionType::Shift, 34}}},
              {{"<expression>", 61}, {"<factor>", 36}, {"<term>", 30}}}},
            {44, {{{"=", {LR::ActionType::Shift, 62}}}, {}}},
            {45,
             {{{"!", {LR::ActionType::Shift, 31}},
               {"(", {LR::ActionType::Shift, 32}},
               {"identifier", {LR::ActionType::Shift, 33}},
               {"literal", {LR::ActionType::Shift, 34}}},
              {{"<expression>", 63}, {"<factor>", 36}, {"<term>", 30}}}},
            {46,
             {{{"!", {LR::ActionType::Shift, 31}},
               {"(", {LR::ActionType::Shift, 32}},
               {"identifier", {LR::ActionType::Shift, 33}},
               {"literal", {LR::ActionType::Shift, 34}}},
              {{"<expression>", 64}, {"<factor>", 36}, {"<term>", 30}}}},
            {47,
             {{{"!", {LR::ActionType::Shift, 31}},
               {"(", {LR::ActionType::Shift, 32}},
               {"=", {LR::ActionType::Shift, 66}},
               {"identifier", {LR::ActionType::Shift, 33}},
               {"literal", {LR::ActionType::Shift, 34}}},
              {{"<expression>", 65}, {"<factor>", 36}, {"<term>", 30}}}},
            {48, {{{"=", {LR::ActionType::Shift, 67}}}, {}}},
            {49,
             {{{"!", {LR::ActionType::Shift, 31}},
               {"(", {LR::ActionType::Shift, 32}},
               {"=", {LR::ActionType::Shift, 69}},
               {"identifier", {LR::ActionType::Shift, 33}},
               {"literal", {LR::ActionType::Shift, 34}}},
              {{"<expression>", 68}, {"<factor>", 36}, {"<term>", 30}}}},
            {50,
             {{{"!", {LR::ActionType::Reduce, 17}},
               {"$", {LR::ActionType::Reduce, 17}},
               {")", {LR::ActionType::Reduce, 17}},
               {"*", {LR::ActionType::Reduce, 17}},
               {"+", {LR::ActionType::Reduce, 17}},
               {",", {LR::ActionType::Reduce, 17}},
               {"-", {LR::ActionType::Reduce, 17}},
               {"/", {LR::ActionType::Reduce, 17}},
               {";", {LR::ActionType::Reduce, 17}},
               {"<", {LR::ActionType::Reduce, 17}},
               {"=", {LR::ActionType::Reduce, 17}},
               {">", {LR::ActionType::Reduce, 17}},
               {"{", {LR::ActionType::Reduce, 17}}},
              {}}},
            {51, {{{")", {LR::ActionType::Shift, 70}}}, {}}},
            {52,
             {{{"identifier", {LR::ActionType::Shift, 14}},
               {"if", {LR::ActionType::Shift, 18}},
               {"let", {LR::ActionType::Shift, 15}},
               {"return", {LR::ActionType::Shift, 19}}},
              {{"<assignment>", 20},
               {"<body>", 71},
               {"<function_call>", 21},
               {"<if>", 22},
               {"<return>", 23},
               {"<statement>", 16}}}},
            {53,
             {{{"!", {LR::ActionType::Shift, 31}},
               {"(", {LR::ActionType::Shift, 32}},
               {"identifier", {LR::ActionType::Shift, 33}},
               {"literal", {LR::ActionType::Shift, 34}}},
              {{"<factor>", 36}, {"<term>", 72}}}},
            {54,
             {{{"!", {LR::ActionType::Shift, 31}},
               {"(", {LR::ActionType::Shift, 32}},
               {"identifier", {LR::ActionType::Shift, 33}},
               {"literal", {LR::ActionType::Shift, 34}}},
              {{"<factor>", 36}, {"<term>", 73}}}},
            {55, {{{"$", {LR::ActionType::Reduce, 29}}, {"}", {LR::ActionType::Reduce, 29}}}, {}}},
            {56, {{{"$", {LR::ActionType::Reduce, 22}}}, {}}},
            {57, {{{"$", {LR::ActionType::Reduce, 2}}, {"}", {LR::ActionType::Reduce, 2}}}, {}}},
            {58,
             {{{"!", {LR::ActionType::Shift, 31}},
               {"(", {LR::ActionType::Shift, 32}},
               {"identifier", {LR::ActionType::Shift, 33}},
               {"literal", {LR::ActionType::Shift, 34}}},
              {{"<call_arguments>", 74}, {"<expression>", 40}, {"<factor>", 36}, {"<term>", 30}}}},
            {59, {{{"$", {LR::ActionType::Reduce, 23}}, {"}", {LR::ActionType::Reduce, 23}}}, {}}},
            {60, {{{";", {LR::ActionType::Shift, 75}}}, {}}},
            {61, {{{";", {LR::ActionType::Shift, 76}}}, {}}},
            {62,
             {{{"!", {LR::ActionType::Shift, 31}},
               {"(", {LR::ActionType::Shift, 32}},
               {"identifier", {LR::ActionType::Shift, 33}},
               {"literal", {LR::ActionType::Shift, 34}}},
              {{"<expression>", 77}, {"<factor>", 36}, {"<term>", 30}}}},
            {63,
             {{{"!", {LR::ActionType::Reduce, 10}},
               {"$", {LR::ActionType::Reduce, 10}},
               {")", {LR::ActionType::Reduce, 10}},
               {"*", {LR::ActionType::Reduce, 10}},
               {"+", {LR::ActionType::Reduce, 10}},
               {",", {LR::ActionType::Reduce, 10}},
               {"-", {LR::ActionType::Reduce, 10}},
               {"/", {LR::ActionType::Reduce, 10}},
               {";", {LR::ActionType::Reduce, 10}},
               {"<", {LR::ActionType::Reduce, 10}},
               {"=", {LR::ActionType::Reduce, 10}},
               {">", {LR::ActionType::Reduce, 10}},
               {"{", {LR::ActionType::Reduce, 10}}},
              {}}},
            {64,
             {{{"!", {LR::ActionType::Reduce, 11}},
               {"$", {LR::ActionType::Reduce, 11}},
               {")", {LR::ActionType::Reduce, 11}},
               {"*", {LR::ActionType::Reduce, 11}},
               {"+", {LR::ActionType::Reduce, 11}},
               {",", {LR::ActionType::Reduce, 11}},
               {"-", {LR::ActionType::Reduce, 11}},
               {"/", {LR::ActionType::Reduce, 11}},
               {";", {LR::ActionType::Reduce, 11}},
               {"<", {LR::ActionType::Reduce, 11}},
               {"=", {LR::ActionType::Reduce, 11}},
               {">", {LR::ActionType::Reduce, 11}},
               {"{", {LR::ActionType::Reduce, 11}}},
              {}}},
            {65,
             {{{"!", {LR::ActionType::Reduce, 12}},
               {"$", {LR::ActionType::Reduce, 12}},
               {")", {LR::ActionType::Reduce, 12}},
               {"*", {LR::ActionType::Reduce, 12}},
               {"+", {LR::ActionType::Reduce, 12}},
               {",", {LR::ActionType::Reduce, 12}},
               {"-", {LR::ActionType::Reduce, 12}},
               {"/", {LR::ActionType::Reduce, 12}},
               {";", {LR::ActionType::Reduce, 12}},
               {"<", {LR::ActionType::Reduce, 12}},
               {"=", {LR::ActionType::Reduce, 12}},
               {">", {LR::ActionType::Reduce, 12}},
               {"{", {LR::ActionType::Reduce, 12}}},
              {}}},
            {66,
             {{{"!", {LR::ActionType::Shift, 31}},
               {"(", {LR::ActionType::Shift, 32}},
               {"identifier", {LR::ActionType::Shift, 33}},
               {"literal", {LR::ActionType::Shift, 34}}},
              {{"<expression>", 78}, {"<factor>", 36}, {"<term>", 30}}}},
            {67,
             {{{"!", {LR::ActionType::Shift, 31}},
               {"(", {LR::ActionType::Shift, 32}},
               {"identifier", {LR::ActionType::Shift, 33}},
               {"literal", {LR::ActionType::Shift, 34}}},
              {{"<expression>", 79}, {"<factor>", 36}, {"<term>", 30}}}},
            {68,
             {{{"!", {LR::ActionType::Reduce, 15}},
               {"$", {LR::ActionType::Reduce, 15}},
               {")", {LR::ActionType::Reduce, 15}},
               {"*", {LR::ActionType::Reduce, 15}},
               {"+", {LR::ActionType::Reduce, 15}},
               {",", {LR::ActionType::Reduce, 15}},
               {"-", {LR::ActionType::Reduce, 15}},
               {"/", {LR::ActionType::Reduce, 15}},
               {";", {LR::ActionType::Reduce, 15}},
               {"<", {LR::ActionType::Reduce, 15}},
               {"=", {LR::ActionType::Reduce, 15}},
               {">", {LR::ActionType::Reduce, 15}},
               {"{", {LR::ActionType::Reduce, 15}}},
              {}}},
            {69,
             {{{"!", {LR::ActionType::Shift, 31}},
               {"(", {LR::ActionType::Shift, 32}},
               {"identifier", {LR::ActionType::Shift, 33}},
               {"literal", {LR::ActionType::Shift, 34}}},
              {{"<expression>", 80}, {"<factor>", 36}, {"<term>", 30}}}},
            {70,
             {{{"!", {LR::ActionType::Reduce, 18}},
               {"$", {LR::ActionType::Reduce, 18}},
               {")", {LR::ActionType::Reduce, 18}},
               {"*", {LR::ActionType::Reduce, 18}},
               {"+", {LR::ActionType::Reduce, 18}},
               {",", {LR::ActionType::Reduce, 18}},
               {"-", {LR::ActionType::Reduce, 18}},
               {"/", {LR::ActionType::Reduce, 18}},
               {";", {LR::ActionType::Reduce, 18}},
               {"<", {LR::ActionType::Reduce, 18}},
               {"=", {LR::ActionType::Reduce, 18}},
               {">", {LR::ActionType::Reduce, 18}},
               {"{", {LR::ActionType::Reduce, 18}}},
              {}}},
            {71, {{{"}", {LR::ActionType::Shift, 81}}}, {}}},
            {72,
             {{{"!", {LR::ActionType::Reduce, 35}},
               {"$", {LR::ActionType::Reduce, 35}},
               {")", {LR::ActionType::Reduce, 35}},
               {"*", {LR::ActionType::Reduce, 35}},
               {"+", {LR::ActionType::Reduce, 35}},
               {",", {LR::ActionType::Reduce, 35}},
               {"-", {LR::ActionType::Reduce, 35}},
               {"/", {LR::ActionType::Reduce, 35}},
               {";", {LR::ActionType::Reduce, 35}},
               {"<", {LR::ActionType::Reduce, 35}},
               {"=", {LR::ActionType::Reduce, 35}},
               {">", {LR::ActionType::Reduce, 35}},
               {"{", {LR::ActionType::Reduce, 35}}},
              {}}},
            {73,
             {{{"!", {LR::ActionType::Reduce, 36}},
               {"$", {LR::ActionType::Reduce, 36}},
               {")", {LR::ActionType::Reduce, 36}},
               {"*", {LR::ActionType::Reduce, 36}},
               {"+", {LR::ActionType::Reduce, 36}},
               {",", {LR::ActionType::Reduce, 36}},
               {"-", {LR::ActionType::Reduce, 36}},
               {"/", {LR::ActionType::Reduce, 36}},
               {";", {LR::ActionType::Reduce, 36}},
               {"<", {LR::ActionType::Reduce, 36}},
               {"=", {LR::ActionType::Reduce, 36}},
               {">", {LR::ActionType::Reduce, 36}},
               {"{", {LR::ActionType::Reduce, 36}}},
              {}}},
            {74, {{{"$", {LR::ActionType::Reduce, 7}}, {")", {LR::ActionType::Reduce, 7}}}, {}}},
            {75, {{{"$", {LR::ActionType::Reduce, 24}}, {"}", {LR::ActionType::Reduce, 24}}}, {}}},
            {76, {{{"$", {LR::ActionType::Reduce, 3}}, {"}", {LR::ActionType::Reduce, 3}}}, {}}},
            {77,
             {{{"!", {LR::ActionType::Reduce, 9}},
               {"$", {LR::ActionType::Reduce, 9}},
               {")", {LR::ActionType::Reduce, 9}},
               {"*", {LR::ActionType::Reduce, 9}},
               {"+", {LR::ActionType::Reduce, 9}},
               {",", {LR::ActionType::Reduce, 9}},
               {"-", {LR::ActionType::Reduce, 9}},
               {"/", {LR::ActionType::Reduce, 9}},
               {";", {LR::ActionType::Reduce, 9}},
               {"<", {LR::ActionType::Reduce, 9}},
               {"=", {LR::ActionType::Reduce, 9}},
               {">", {LR::ActionType::Reduce, 9}},
               {"{", {LR::ActionType::Reduce, 9}}},
              {}}},
            {78,
             {{{"!", {LR::ActionType::Reduce, 13}},
               {"$", {LR::ActionType::Reduce, 13}},
               {")", {LR::ActionType::Reduce, 13}},
               {"*", {LR::ActionType::Reduce, 13}},
               {"+", {LR::ActionType::Reduce, 13}},
               {",", {LR::ActionType::Reduce, 13}},
               {"-", {LR::ActionType::Reduce, 13}},
               {"/", {LR::ActionType::Reduce, 13}},
               {";", {LR::ActionType::Reduce, 13}},
               {"<", {LR::ActionType::Reduce, 13}},
               {"=", {LR::ActionType::Reduce, 13}},
               {">", {LR::ActionType::Reduce, 13}},
               {"{", {LR::ActionType::Reduce, 13}}},
              {}}},
            {79,
             {{{"!", {LR::ActionType::Reduce, 14}},
               {"$", {LR::ActionType::Reduce, 14}},
               {")", {LR::ActionType::Reduce, 14}},
               {"*", {LR::ActionType::Reduce, 14}},
               {"+", {LR::ActionType::Reduce, 14}},
               {",", {LR::ActionType::Reduce, 14}},
               {"-", {LR::ActionType::Reduce, 14}},
               {"/", {LR::ActionType::Reduce, 14}},
               {";", {LR::ActionType::Reduce, 14}},
               {"<", {LR::ActionType::Reduce, 14}},
               {"=", {LR::ActionType::Reduce, 14}},
               {">", {LR::ActionType::Reduce, 14}},
               {"{", {LR::ActionType::Reduce, 14}}},
              {}}},
            {80,
             {{{"!", {LR::ActionType::Reduce, 16}},
               {"$", {LR::ActionType::Reduce, 16}},
               {")", {LR::ActionType::Reduce, 16}},
               {"*", {LR::ActionType::Reduce, 16}},
               {"+", {LR::ActionType::Reduce, 16}},
               {",", {LR::ActionType::Reduce, 16}},
               {"-", {LR::ActionType::Reduce, 16}},
               {"/", {LR::ActionType::Reduce, 16}},
               {";", {LR::ActionType::Reduce, 16}},
               {"<", {LR::ActionType::Reduce, 16}},
               {"=", {LR::ActionType::Reduce, 16}},
               {">", {LR::ActionType::Reduce, 16}},
               {"{", {LR::ActionType::Reduce, 16}}},
              {}}},
            {81,
             {{{"$", {LR::ActionType::Reduce, 25}},
               {"else", {LR::ActionType::Shift, 82}},
               {"}", {LR::ActionType::Reduce, 25}}},
              {}}},
            {82, {{{"{", {LR::ActionType::Shift, 83}}}, {}}},
            {83,
             {{{"identifier", {LR::ActionType::Shift, 14}},
               {"if", {LR::ActionType::Shift, 18}},
               {"let", {LR::ActionType::Shift, 15}},
               {"return", {LR::ActionType::Shift, 19}}},
              {{"<assignment>", 20},
               {"<body>", 84},
               {"<function_call>", 21},
               {"<if>", 22},
               {"<return>", 23},
               {"<statement>", 16}}}},
            {84, {{{"}", {LR::ActionType::Shift, 85}}}, {}}},
            {85, {{{"$", {LR::ActionType::Reduce, 26}}, {"}", {LR::ActionType::Reduce, 26}}}, {}}}};

        CHECK_EQ(table, get_table());
    }
}
