#include "doctest/doctest.h"

#include "machines/CFG.h"
#include "parser/lr.h"

class LRTest {
protected:
    LR lr{};

protected:
    LR::ItemSet closure(const LR::ItemSet& item, const std::string& separator, const CFG& cfg) {
        return LR::closure(item, separator, cfg);
    }

    void setup(const CFG& cfg) { this->lr = LR(cfg); }

    const LR::ParsingTable& get_table() const { return this->lr.table; }
};

TEST_SUITE("LRTests") {
    TEST_CASE_FIXTURE(LRTest, "[LRTests] closure") {
        const std::string separator("·");
        const LR::ItemSet start_item_set{{LR::Item{"S", {separator, "A", "A"}}}};

        const CFG cfg("./test/res/input/CFG2.json");

        CHECK_EQ(closure(start_item_set, separator, cfg),
                 LR::ItemSet{{{"A", {"·", "a", "A"}}, {"A", {"·", "b"}}, {"S", {"·", "A", "A"}}}});
    }

    TEST_CASE_FIXTURE(LRTest, "[LRTests] parsing_table") {
        const CFG cfg("./test/res/input/CFG2.json");
        setup(cfg);

        LR::ParsingTable table{
            {0, {{{"a", {LR::ActionType::Shift, 1}}, {"b", {LR::ActionType::Shift, 2}}}, {{"A", 3}, {"S", 4}}}},
            {1, {{{"a", {LR::ActionType::Shift, 1}}, {"b", {LR::ActionType::Shift, 2}}}, {{"A", 5}}}},
            {2,
             {{{"$", {LR::ActionType::Reduce, 1}},
               {"a", {LR::ActionType::Reduce, 1}},
               {"b", {LR::ActionType::Reduce, 1}}},
              {}}},
            {3, {{{"a", {LR::ActionType::Shift, 1}}, {"b", {LR::ActionType::Shift, 2}}}, {{"A", 6}}}},
            {4, {{{"$", {LR::ActionType::Accept, 0}}}, {}}},
            {5,
             {{{"$", {LR::ActionType::Reduce, 0}},
               {"a", {LR::ActionType::Reduce, 0}},
               {"b", {LR::ActionType::Reduce, 0}}},
              {}}},
            {6, {{{"$", {LR::ActionType::Reduce, 2}}}, {}}}};

        CHECK_EQ(table, get_table());
    }

    TEST_CASE_FIXTURE(LRTest, "[LRTests] table_edge_case_0") {
        const CFG cfg = CFG::parse_ebnf("test/res/input/EBNF0.txt");
        setup(cfg);

        const LR::ParsingTable table{
            {0, {{{"literal", {LR::ActionType::Shift, 3}}}, {{"<assignment>", 4}, {"<expression>", 1}, {"<term>", 2}}}},
            {1, {{{";", {LR::ActionType::Shift, 5}}}, {}}},
            {2, {{{"+", {LR::ActionType::Shift, 6}}, {";", {LR::ActionType::Reduce, 1}}}, {}}},
            {3,
             {{{"*", {LR::ActionType::Shift, 7}},
               {"+", {LR::ActionType::Reduce, 3}},
               {";", {LR::ActionType::Reduce, 3}}},
              {}}},
            {4, {{{"$", {LR::ActionType::Accept, 0}}}, {}}},
            {5, {{{"$", {LR::ActionType::Reduce, 0}}}, {}}},
            {6, {{{"literal", {LR::ActionType::Shift, 3}}}, {{"<expression>", 8}, {"<term>", 2}}}},
            {7, {{{"literal", {LR::ActionType::Shift, 3}}}, {{"<term>", 9}}}},
            {8, {{{";", {LR::ActionType::Reduce, 2}}}, {}}},
            {9, {{{"+", {LR::ActionType::Reduce, 4}}, {";", {LR::ActionType::Reduce, 4}}}, {}}}};

        CHECK_EQ(table, get_table());
    }

    TEST_CASE_FIXTURE(LRTest, "[LRTests] pai_parse_table") {
        const CFG cfg = CFG::parse_ebnf("test/res/input/EBNF2CFG.txt");
        setup(cfg);

        const LR::ParsingTable table{
            {0, {{{"fn", {LR::ActionType::Shift, 1}}}, {{"<function>", 2}, {"<program>", 3}}}},
            {1, {{{"identifier", {LR::ActionType::Shift, 4}}}, {}}},
            {2,
             {{{"$", {LR::ActionType::Reduce, 30}}, {"fn", {LR::ActionType::Shift, 1}}},
              {{"<function>", 2}, {"<program>", 5}}}},
            {3, {{{"$", {LR::ActionType::Accept, 0}}}, {}}},
            {4, {{{"(", {LR::ActionType::Shift, 6}}}, {}}},
            {5, {{{"$", {LR::ActionType::Reduce, 31}}}, {}}},
            {6,
             {{{")", {LR::ActionType::Shift, 8}}, {"identifier", {LR::ActionType::Shift, 7}}}, {{"<arguments>", 9}}}},
            {7, {{{")", {LR::ActionType::Reduce, 0}}, {",", {LR::ActionType::Shift, 10}}}, {}}},
            {8, {{{"{", {LR::ActionType::Shift, 11}}}, {}}},
            {9, {{{")", {LR::ActionType::Shift, 12}}}, {}}},
            {10, {{{"identifier", {LR::ActionType::Shift, 7}}}, {{"<arguments>", 13}}}},
            {11,
             {{{"identifier", {LR::ActionType::Shift, 14}},
               {"if", {LR::ActionType::Shift, 19}},
               {"let", {LR::ActionType::Shift, 15}},
               {"return", {LR::ActionType::Shift, 20}},
               {"}", {LR::ActionType::Shift, 18}}},
              {{"<assignment>", 21},
               {"<body>", 17},
               {"<function_call>", 22},
               {"<if>", 23},
               {"<return>", 24},
               {"<statement>", 16}}}},
            {12, {{{"{", {LR::ActionType::Shift, 25}}}, {}}},
            {13, {{{")", {LR::ActionType::Reduce, 1}}}, {}}},
            {14, {{{"(", {LR::ActionType::Shift, 27}}, {"=", {LR::ActionType::Shift, 26}}}, {}}},
            {15, {{{"identifier", {LR::ActionType::Shift, 28}}}, {}}},
            {16,
             {{{"identifier", {LR::ActionType::Shift, 14}},
               {"if", {LR::ActionType::Shift, 19}},
               {"let", {LR::ActionType::Shift, 15}},
               {"return", {LR::ActionType::Shift, 20}},
               {"}", {LR::ActionType::Reduce, 4}}},
              {{"<assignment>", 21},
               {"<body>", 29},
               {"<function_call>", 22},
               {"<if>", 23},
               {"<return>", 24},
               {"<statement>", 16}}}},
            {17, {{{"}", {LR::ActionType::Shift, 30}}}, {}}},
            {18, {{{"$", {LR::ActionType::Reduce, 24}}, {"fn", {LR::ActionType::Reduce, 24}}}, {}}},
            {19,
             {{{"!", {LR::ActionType::Shift, 33}},
               {"(", {LR::ActionType::Shift, 34}},
               {"-", {LR::ActionType::Shift, 35}},
               {"identifier", {LR::ActionType::Shift, 37}},
               {"literal", {LR::ActionType::Shift, 38}}},
              {{"<expression>", 31}, {"<factor>", 39}, {"<function_call>", 36}, {"<term>", 32}}}},
            {20,
             {{{"!", {LR::ActionType::Shift, 33}},
               {"(", {LR::ActionType::Shift, 34}},
               {"-", {LR::ActionType::Shift, 35}},
               {"identifier", {LR::ActionType::Shift, 37}},
               {"literal", {LR::ActionType::Shift, 38}}},
              {{"<expression>", 40}, {"<factor>", 39}, {"<function_call>", 36}, {"<term>", 32}}}},
            {21,
             {{{"identifier", {LR::ActionType::Reduce, 33}},
               {"if", {LR::ActionType::Reduce, 33}},
               {"let", {LR::ActionType::Reduce, 33}},
               {"return", {LR::ActionType::Reduce, 33}},
               {"}", {LR::ActionType::Reduce, 33}}},
              {}}},
            {22, {{{";", {LR::ActionType::Shift, 41}}}, {}}},
            {23,
             {{{"identifier", {LR::ActionType::Reduce, 35}},
               {"if", {LR::ActionType::Reduce, 35}},
               {"let", {LR::ActionType::Reduce, 35}},
               {"return", {LR::ActionType::Reduce, 35}},
               {"}", {LR::ActionType::Reduce, 35}}},
              {}}},
            {24,
             {{{"identifier", {LR::ActionType::Reduce, 36}},
               {"if", {LR::ActionType::Reduce, 36}},
               {"let", {LR::ActionType::Reduce, 36}},
               {"return", {LR::ActionType::Reduce, 36}},
               {"}", {LR::ActionType::Reduce, 36}}},
              {}}},
            {25,
             {{{"identifier", {LR::ActionType::Shift, 14}},
               {"if", {LR::ActionType::Shift, 19}},
               {"let", {LR::ActionType::Shift, 15}},
               {"return", {LR::ActionType::Shift, 20}}},
              {{"<assignment>", 21},
               {"<body>", 42},
               {"<function_call>", 22},
               {"<if>", 23},
               {"<return>", 24},
               {"<statement>", 16}}}},
            {26,
             {{{"!", {LR::ActionType::Shift, 33}},
               {"(", {LR::ActionType::Shift, 34}},
               {"-", {LR::ActionType::Shift, 35}},
               {"identifier", {LR::ActionType::Shift, 37}},
               {"literal", {LR::ActionType::Shift, 38}}},
              {{"<expression>", 43}, {"<factor>", 39}, {"<function_call>", 36}, {"<term>", 32}}}},
            {27,
             {{{"!", {LR::ActionType::Shift, 33}},
               {"(", {LR::ActionType::Shift, 34}},
               {")", {LR::ActionType::Shift, 45}},
               {"-", {LR::ActionType::Shift, 35}},
               {"identifier", {LR::ActionType::Shift, 37}},
               {"literal", {LR::ActionType::Shift, 38}}},
              {{"<call_arguments>", 46},
               {"<expression>", 44},
               {"<factor>", 39},
               {"<function_call>", 36},
               {"<term>", 32}}}},
            {28, {{{"=", {LR::ActionType::Shift, 47}}}, {}}},
            {29, {{{"}", {LR::ActionType::Reduce, 5}}}, {}}},
            {30, {{{"$", {LR::ActionType::Reduce, 23}}, {"fn", {LR::ActionType::Reduce, 23}}}, {}}},
            {31,
             {{{"!", {LR::ActionType::Shift, 48}},
               {"+", {LR::ActionType::Shift, 49}},
               {"-", {LR::ActionType::Shift, 50}},
               {"<", {LR::ActionType::Shift, 51}},
               {"=", {LR::ActionType::Shift, 52}},
               {">", {LR::ActionType::Shift, 53}},
               {"{", {LR::ActionType::Shift, 54}}},
              {}}},
            {32,
             {{{"!", {LR::ActionType::Reduce, 16}},
               {")", {LR::ActionType::Reduce, 16}},
               {"*", {LR::ActionType::Shift, 55}},
               {"+", {LR::ActionType::Reduce, 16}},
               {",", {LR::ActionType::Reduce, 16}},
               {"-", {LR::ActionType::Reduce, 16}},
               {"/", {LR::ActionType::Shift, 56}},
               {";", {LR::ActionType::Reduce, 16}},
               {"<", {LR::ActionType::Reduce, 16}},
               {"=", {LR::ActionType::Reduce, 16}},
               {">", {LR::ActionType::Reduce, 16}},
               {"{", {LR::ActionType::Reduce, 16}}},
              {}}},
            {33, {{{"(", {LR::ActionType::Shift, 57}}}, {}}},
            {34,
             {{{"!", {LR::ActionType::Shift, 33}},
               {"(", {LR::ActionType::Shift, 34}},
               {"-", {LR::ActionType::Shift, 35}},
               {"identifier", {LR::ActionType::Shift, 37}},
               {"literal", {LR::ActionType::Shift, 38}}},
              {{"<expression>", 58}, {"<factor>", 39}, {"<function_call>", 36}, {"<term>", 32}}}},
            {35,
             {{{"!", {LR::ActionType::Shift, 33}},
               {"(", {LR::ActionType::Shift, 34}},
               {"-", {LR::ActionType::Shift, 35}},
               {"identifier", {LR::ActionType::Shift, 37}},
               {"literal", {LR::ActionType::Shift, 38}}},
              {{"<factor>", 59}, {"<function_call>", 36}}}},
            {36,
             {{{"!", {LR::ActionType::Reduce, 20}},
               {")", {LR::ActionType::Reduce, 20}},
               {"*", {LR::ActionType::Reduce, 20}},
               {"+", {LR::ActionType::Reduce, 20}},
               {",", {LR::ActionType::Reduce, 20}},
               {"-", {LR::ActionType::Reduce, 20}},
               {"/", {LR::ActionType::Reduce, 20}},
               {";", {LR::ActionType::Reduce, 20}},
               {"<", {LR::ActionType::Reduce, 20}},
               {"=", {LR::ActionType::Reduce, 20}},
               {">", {LR::ActionType::Reduce, 20}},
               {"{", {LR::ActionType::Reduce, 20}}},
              {}}},
            {37,
             {{{"!", {LR::ActionType::Reduce, 21}},
               {"(", {LR::ActionType::Shift, 27}},
               {")", {LR::ActionType::Reduce, 21}},
               {"*", {LR::ActionType::Reduce, 21}},
               {"+", {LR::ActionType::Reduce, 21}},
               {",", {LR::ActionType::Reduce, 21}},
               {"-", {LR::ActionType::Reduce, 21}},
               {"/", {LR::ActionType::Reduce, 21}},
               {";", {LR::ActionType::Reduce, 21}},
               {"<", {LR::ActionType::Reduce, 21}},
               {"=", {LR::ActionType::Reduce, 21}},
               {">", {LR::ActionType::Reduce, 21}},
               {"{", {LR::ActionType::Reduce, 21}}},
              {}}},
            {38,
             {{{"!", {LR::ActionType::Reduce, 22}},
               {")", {LR::ActionType::Reduce, 22}},
               {"*", {LR::ActionType::Reduce, 22}},
               {"+", {LR::ActionType::Reduce, 22}},
               {",", {LR::ActionType::Reduce, 22}},
               {"-", {LR::ActionType::Reduce, 22}},
               {"/", {LR::ActionType::Reduce, 22}},
               {";", {LR::ActionType::Reduce, 22}},
               {"<", {LR::ActionType::Reduce, 22}},
               {"=", {LR::ActionType::Reduce, 22}},
               {">", {LR::ActionType::Reduce, 22}},
               {"{", {LR::ActionType::Reduce, 22}}},
              {}}},
            {39,
             {{{"!", {LR::ActionType::Reduce, 37}},
               {")", {LR::ActionType::Reduce, 37}},
               {"*", {LR::ActionType::Reduce, 37}},
               {"+", {LR::ActionType::Reduce, 37}},
               {",", {LR::ActionType::Reduce, 37}},
               {"-", {LR::ActionType::Reduce, 37}},
               {"/", {LR::ActionType::Reduce, 37}},
               {";", {LR::ActionType::Reduce, 37}},
               {"<", {LR::ActionType::Reduce, 37}},
               {"=", {LR::ActionType::Reduce, 37}},
               {">", {LR::ActionType::Reduce, 37}},
               {"{", {LR::ActionType::Reduce, 37}}},
              {}}},
            {40,
             {{{"!", {LR::ActionType::Shift, 48}},
               {"+", {LR::ActionType::Shift, 49}},
               {"-", {LR::ActionType::Shift, 50}},
               {";", {LR::ActionType::Shift, 60}},
               {"<", {LR::ActionType::Shift, 51}},
               {"=", {LR::ActionType::Shift, 52}},
               {">", {LR::ActionType::Shift, 53}}},
              {}}},
            {41,
             {{{"identifier", {LR::ActionType::Reduce, 34}},
               {"if", {LR::ActionType::Reduce, 34}},
               {"let", {LR::ActionType::Reduce, 34}},
               {"return", {LR::ActionType::Reduce, 34}},
               {"}", {LR::ActionType::Reduce, 34}}},
              {}}},
            {42, {{{"}", {LR::ActionType::Shift, 61}}}, {}}},
            {43,
             {{{"!", {LR::ActionType::Shift, 48}},
               {"+", {LR::ActionType::Shift, 49}},
               {"-", {LR::ActionType::Shift, 50}},
               {";", {LR::ActionType::Shift, 62}},
               {"<", {LR::ActionType::Shift, 51}},
               {"=", {LR::ActionType::Shift, 52}},
               {">", {LR::ActionType::Shift, 53}}},
              {}}},
            {44,
             {{{"!", {LR::ActionType::Shift, 48}},
               {")", {LR::ActionType::Reduce, 6}},
               {"+", {LR::ActionType::Shift, 49}},
               {",", {LR::ActionType::Shift, 63}},
               {"-", {LR::ActionType::Shift, 50}},
               {"<", {LR::ActionType::Shift, 51}},
               {"=", {LR::ActionType::Shift, 52}},
               {">", {LR::ActionType::Shift, 53}}},
              {}}},
            {45,
             {{{"!", {LR::ActionType::Reduce, 26}},
               {")", {LR::ActionType::Reduce, 26}},
               {"*", {LR::ActionType::Reduce, 26}},
               {"+", {LR::ActionType::Reduce, 26}},
               {",", {LR::ActionType::Reduce, 26}},
               {"-", {LR::ActionType::Reduce, 26}},
               {"/", {LR::ActionType::Reduce, 26}},
               {";", {LR::ActionType::Reduce, 26}},
               {"<", {LR::ActionType::Reduce, 26}},
               {"=", {LR::ActionType::Reduce, 26}},
               {">", {LR::ActionType::Reduce, 26}},
               {"{", {LR::ActionType::Reduce, 26}}},
              {}}},
            {46, {{{")", {LR::ActionType::Shift, 64}}}, {}}},
            {47,
             {{{"!", {LR::ActionType::Shift, 33}},
               {"(", {LR::ActionType::Shift, 34}},
               {"-", {LR::ActionType::Shift, 35}},
               {"identifier", {LR::ActionType::Shift, 37}},
               {"literal", {LR::ActionType::Shift, 38}}},
              {{"<expression>", 65}, {"<factor>", 39}, {"<function_call>", 36}, {"<term>", 32}}}},
            {48, {{{"=", {LR::ActionType::Shift, 66}}}, {}}},
            {49,
             {{{"!", {LR::ActionType::Shift, 33}},
               {"(", {LR::ActionType::Shift, 34}},
               {"-", {LR::ActionType::Shift, 35}},
               {"identifier", {LR::ActionType::Shift, 37}},
               {"literal", {LR::ActionType::Shift, 38}}},
              {{"<factor>", 39}, {"<function_call>", 36}, {"<term>", 67}}}},
            {50,
             {{{"!", {LR::ActionType::Shift, 33}},
               {"(", {LR::ActionType::Shift, 34}},
               {"-", {LR::ActionType::Shift, 35}},
               {"identifier", {LR::ActionType::Shift, 37}},
               {"literal", {LR::ActionType::Shift, 38}}},
              {{"<factor>", 39}, {"<function_call>", 36}, {"<term>", 68}}}},
            {51,
             {{{"!", {LR::ActionType::Shift, 33}},
               {"(", {LR::ActionType::Shift, 34}},
               {"-", {LR::ActionType::Shift, 35}},
               {"=", {LR::ActionType::Shift, 70}},
               {"identifier", {LR::ActionType::Shift, 37}},
               {"literal", {LR::ActionType::Shift, 38}}},
              {{"<factor>", 39}, {"<function_call>", 36}, {"<term>", 69}}}},
            {52, {{{"=", {LR::ActionType::Shift, 71}}}, {}}},
            {53,
             {{{"!", {LR::ActionType::Shift, 33}},
               {"(", {LR::ActionType::Shift, 34}},
               {"-", {LR::ActionType::Shift, 35}},
               {"=", {LR::ActionType::Shift, 73}},
               {"identifier", {LR::ActionType::Shift, 37}},
               {"literal", {LR::ActionType::Shift, 38}}},
              {{"<factor>", 39}, {"<function_call>", 36}, {"<term>", 72}}}},
            {54,
             {{{"identifier", {LR::ActionType::Shift, 14}},
               {"if", {LR::ActionType::Shift, 19}},
               {"let", {LR::ActionType::Shift, 15}},
               {"return", {LR::ActionType::Shift, 20}}},
              {{"<assignment>", 21},
               {"<body>", 74},
               {"<function_call>", 22},
               {"<if>", 23},
               {"<return>", 24},
               {"<statement>", 16}}}},
            {55,
             {{{"!", {LR::ActionType::Shift, 33}},
               {"(", {LR::ActionType::Shift, 34}},
               {"-", {LR::ActionType::Shift, 35}},
               {"identifier", {LR::ActionType::Shift, 37}},
               {"literal", {LR::ActionType::Shift, 38}}},
              {{"<factor>", 75}, {"<function_call>", 36}}}},
            {56,
             {{{"!", {LR::ActionType::Shift, 33}},
               {"(", {LR::ActionType::Shift, 34}},
               {"-", {LR::ActionType::Shift, 35}},
               {"identifier", {LR::ActionType::Shift, 37}},
               {"literal", {LR::ActionType::Shift, 38}}},
              {{"<factor>", 76}, {"<function_call>", 36}}}},
            {57,
             {{{"!", {LR::ActionType::Shift, 33}},
               {"(", {LR::ActionType::Shift, 34}},
               {"-", {LR::ActionType::Shift, 35}},
               {"identifier", {LR::ActionType::Shift, 37}},
               {"literal", {LR::ActionType::Shift, 38}}},
              {{"<expression>", 77}, {"<factor>", 39}, {"<function_call>", 36}, {"<term>", 32}}}},
            {58,
             {{{"!", {LR::ActionType::Shift, 48}},
               {")", {LR::ActionType::Shift, 78}},
               {"+", {LR::ActionType::Shift, 49}},
               {"-", {LR::ActionType::Shift, 50}},
               {"<", {LR::ActionType::Shift, 51}},
               {"=", {LR::ActionType::Shift, 52}},
               {">", {LR::ActionType::Shift, 53}}},
              {}}},
            {59,
             {{{"!", {LR::ActionType::Reduce, 19}},
               {")", {LR::ActionType::Reduce, 19}},
               {"*", {LR::ActionType::Reduce, 19}},
               {"+", {LR::ActionType::Reduce, 19}},
               {",", {LR::ActionType::Reduce, 19}},
               {"-", {LR::ActionType::Reduce, 19}},
               {"/", {LR::ActionType::Reduce, 19}},
               {";", {LR::ActionType::Reduce, 19}},
               {"<", {LR::ActionType::Reduce, 19}},
               {"=", {LR::ActionType::Reduce, 19}},
               {">", {LR::ActionType::Reduce, 19}},
               {"{", {LR::ActionType::Reduce, 19}}},
              {}}},
            {60,
             {{{"identifier", {LR::ActionType::Reduce, 32}},
               {"if", {LR::ActionType::Reduce, 32}},
               {"let", {LR::ActionType::Reduce, 32}},
               {"return", {LR::ActionType::Reduce, 32}},
               {"}", {LR::ActionType::Reduce, 32}}},
              {}}},
            {61, {{{"$", {LR::ActionType::Reduce, 25}}, {"fn", {LR::ActionType::Reduce, 25}}}, {}}},
            {62,
             {{{"identifier", {LR::ActionType::Reduce, 2}},
               {"if", {LR::ActionType::Reduce, 2}},
               {"let", {LR::ActionType::Reduce, 2}},
               {"return", {LR::ActionType::Reduce, 2}},
               {"}", {LR::ActionType::Reduce, 2}}},
              {}}},
            {63,
             {{{"!", {LR::ActionType::Shift, 33}},
               {"(", {LR::ActionType::Shift, 34}},
               {"-", {LR::ActionType::Shift, 35}},
               {"identifier", {LR::ActionType::Shift, 37}},
               {"literal", {LR::ActionType::Shift, 38}}},
              {{"<call_arguments>", 79},
               {"<expression>", 44},
               {"<factor>", 39},
               {"<function_call>", 36},
               {"<term>", 32}}}},
            {64,
             {{{"!", {LR::ActionType::Reduce, 27}},
               {")", {LR::ActionType::Reduce, 27}},
               {"*", {LR::ActionType::Reduce, 27}},
               {"+", {LR::ActionType::Reduce, 27}},
               {",", {LR::ActionType::Reduce, 27}},
               {"-", {LR::ActionType::Reduce, 27}},
               {"/", {LR::ActionType::Reduce, 27}},
               {";", {LR::ActionType::Reduce, 27}},
               {"<", {LR::ActionType::Reduce, 27}},
               {"=", {LR::ActionType::Reduce, 27}},
               {">", {LR::ActionType::Reduce, 27}},
               {"{", {LR::ActionType::Reduce, 27}}},
              {}}},
            {65,
             {{{"!", {LR::ActionType::Shift, 48}},
               {"+", {LR::ActionType::Shift, 49}},
               {"-", {LR::ActionType::Shift, 50}},
               {";", {LR::ActionType::Shift, 80}},
               {"<", {LR::ActionType::Shift, 51}},
               {"=", {LR::ActionType::Shift, 52}},
               {">", {LR::ActionType::Shift, 53}}},
              {}}},
            {66,
             {{{"!", {LR::ActionType::Shift, 33}},
               {"(", {LR::ActionType::Shift, 34}},
               {"-", {LR::ActionType::Shift, 35}},
               {"identifier", {LR::ActionType::Shift, 37}},
               {"literal", {LR::ActionType::Shift, 38}}},
              {{"<factor>", 39}, {"<function_call>", 36}, {"<term>", 81}}}},
            {67,
             {{{"!", {LR::ActionType::Reduce, 9}},
               {")", {LR::ActionType::Reduce, 9}},
               {"*", {LR::ActionType::Shift, 55}},
               {"+", {LR::ActionType::Reduce, 9}},
               {",", {LR::ActionType::Reduce, 9}},
               {"-", {LR::ActionType::Reduce, 9}},
               {"/", {LR::ActionType::Shift, 56}},
               {";", {LR::ActionType::Reduce, 9}},
               {"<", {LR::ActionType::Reduce, 9}},
               {"=", {LR::ActionType::Reduce, 9}},
               {">", {LR::ActionType::Reduce, 9}},
               {"{", {LR::ActionType::Reduce, 9}}},
              {}}},
            {68,
             {{{"!", {LR::ActionType::Reduce, 10}},
               {")", {LR::ActionType::Reduce, 10}},
               {"*", {LR::ActionType::Shift, 55}},
               {"+", {LR::ActionType::Reduce, 10}},
               {",", {LR::ActionType::Reduce, 10}},
               {"-", {LR::ActionType::Reduce, 10}},
               {"/", {LR::ActionType::Shift, 56}},
               {";", {LR::ActionType::Reduce, 10}},
               {"<", {LR::ActionType::Reduce, 10}},
               {"=", {LR::ActionType::Reduce, 10}},
               {">", {LR::ActionType::Reduce, 10}},
               {"{", {LR::ActionType::Reduce, 10}}},
              {}}},
            {69,
             {{{"!", {LR::ActionType::Reduce, 11}},
               {")", {LR::ActionType::Reduce, 11}},
               {"*", {LR::ActionType::Shift, 55}},
               {"+", {LR::ActionType::Reduce, 11}},
               {",", {LR::ActionType::Reduce, 11}},
               {"-", {LR::ActionType::Reduce, 11}},
               {"/", {LR::ActionType::Shift, 56}},
               {";", {LR::ActionType::Reduce, 11}},
               {"<", {LR::ActionType::Reduce, 11}},
               {"=", {LR::ActionType::Reduce, 11}},
               {">", {LR::ActionType::Reduce, 11}},
               {"{", {LR::ActionType::Reduce, 11}}},
              {}}},
            {70,
             {{{"!", {LR::ActionType::Shift, 33}},
               {"(", {LR::ActionType::Shift, 34}},
               {"-", {LR::ActionType::Shift, 35}},
               {"identifier", {LR::ActionType::Shift, 37}},
               {"literal", {LR::ActionType::Shift, 38}}},
              {{"<factor>", 39}, {"<function_call>", 36}, {"<term>", 82}}}},
            {71,
             {{{"!", {LR::ActionType::Shift, 33}},
               {"(", {LR::ActionType::Shift, 34}},
               {"-", {LR::ActionType::Shift, 35}},
               {"identifier", {LR::ActionType::Shift, 37}},
               {"literal", {LR::ActionType::Shift, 38}}},
              {{"<factor>", 39}, {"<function_call>", 36}, {"<term>", 83}}}},
            {72,
             {{{"!", {LR::ActionType::Reduce, 14}},
               {")", {LR::ActionType::Reduce, 14}},
               {"*", {LR::ActionType::Shift, 55}},
               {"+", {LR::ActionType::Reduce, 14}},
               {",", {LR::ActionType::Reduce, 14}},
               {"-", {LR::ActionType::Reduce, 14}},
               {"/", {LR::ActionType::Shift, 56}},
               {";", {LR::ActionType::Reduce, 14}},
               {"<", {LR::ActionType::Reduce, 14}},
               {"=", {LR::ActionType::Reduce, 14}},
               {">", {LR::ActionType::Reduce, 14}},
               {"{", {LR::ActionType::Reduce, 14}}},
              {}}},
            {73,
             {{{"!", {LR::ActionType::Shift, 33}},
               {"(", {LR::ActionType::Shift, 34}},
               {"-", {LR::ActionType::Shift, 35}},
               {"identifier", {LR::ActionType::Shift, 37}},
               {"literal", {LR::ActionType::Shift, 38}}},
              {{"<factor>", 39}, {"<function_call>", 36}, {"<term>", 84}}}},
            {74, {{{"}", {LR::ActionType::Shift, 85}}}, {}}},
            {75,
             {{{"!", {LR::ActionType::Reduce, 38}},
               {")", {LR::ActionType::Reduce, 38}},
               {"*", {LR::ActionType::Reduce, 38}},
               {"+", {LR::ActionType::Reduce, 38}},
               {",", {LR::ActionType::Reduce, 38}},
               {"-", {LR::ActionType::Reduce, 38}},
               {"/", {LR::ActionType::Reduce, 38}},
               {";", {LR::ActionType::Reduce, 38}},
               {"<", {LR::ActionType::Reduce, 38}},
               {"=", {LR::ActionType::Reduce, 38}},
               {">", {LR::ActionType::Reduce, 38}},
               {"{", {LR::ActionType::Reduce, 38}}},
              {}}},
            {76,
             {{{"!", {LR::ActionType::Reduce, 39}},
               {")", {LR::ActionType::Reduce, 39}},
               {"*", {LR::ActionType::Reduce, 39}},
               {"+", {LR::ActionType::Reduce, 39}},
               {",", {LR::ActionType::Reduce, 39}},
               {"-", {LR::ActionType::Reduce, 39}},
               {"/", {LR::ActionType::Reduce, 39}},
               {";", {LR::ActionType::Reduce, 39}},
               {"<", {LR::ActionType::Reduce, 39}},
               {"=", {LR::ActionType::Reduce, 39}},
               {">", {LR::ActionType::Reduce, 39}},
               {"{", {LR::ActionType::Reduce, 39}}},
              {}}},
            {77,
             {{{"!", {LR::ActionType::Shift, 48}},
               {")", {LR::ActionType::Shift, 86}},
               {"+", {LR::ActionType::Shift, 49}},
               {"-", {LR::ActionType::Shift, 50}},
               {"<", {LR::ActionType::Shift, 51}},
               {"=", {LR::ActionType::Shift, 52}},
               {">", {LR::ActionType::Shift, 53}}},
              {}}},
            {78,
             {{{"!", {LR::ActionType::Reduce, 18}},
               {")", {LR::ActionType::Reduce, 18}},
               {"*", {LR::ActionType::Reduce, 18}},
               {"+", {LR::ActionType::Reduce, 18}},
               {",", {LR::ActionType::Reduce, 18}},
               {"-", {LR::ActionType::Reduce, 18}},
               {"/", {LR::ActionType::Reduce, 18}},
               {";", {LR::ActionType::Reduce, 18}},
               {"<", {LR::ActionType::Reduce, 18}},
               {"=", {LR::ActionType::Reduce, 18}},
               {">", {LR::ActionType::Reduce, 18}},
               {"{", {LR::ActionType::Reduce, 18}}},
              {}}},
            {79, {{{")", {LR::ActionType::Reduce, 7}}}, {}}},
            {80,
             {{{"identifier", {LR::ActionType::Reduce, 3}},
               {"if", {LR::ActionType::Reduce, 3}},
               {"let", {LR::ActionType::Reduce, 3}},
               {"return", {LR::ActionType::Reduce, 3}},
               {"}", {LR::ActionType::Reduce, 3}}},
              {}}},
            {81,
             {{{"!", {LR::ActionType::Reduce, 8}},
               {")", {LR::ActionType::Reduce, 8}},
               {"*", {LR::ActionType::Shift, 55}},
               {"+", {LR::ActionType::Reduce, 8}},
               {",", {LR::ActionType::Reduce, 8}},
               {"-", {LR::ActionType::Reduce, 8}},
               {"/", {LR::ActionType::Shift, 56}},
               {";", {LR::ActionType::Reduce, 8}},
               {"<", {LR::ActionType::Reduce, 8}},
               {"=", {LR::ActionType::Reduce, 8}},
               {">", {LR::ActionType::Reduce, 8}},
               {"{", {LR::ActionType::Reduce, 8}}},
              {}}},
            {82,
             {{{"!", {LR::ActionType::Reduce, 12}},
               {")", {LR::ActionType::Reduce, 12}},
               {"*", {LR::ActionType::Shift, 55}},
               {"+", {LR::ActionType::Reduce, 12}},
               {",", {LR::ActionType::Reduce, 12}},
               {"-", {LR::ActionType::Reduce, 12}},
               {"/", {LR::ActionType::Shift, 56}},
               {";", {LR::ActionType::Reduce, 12}},
               {"<", {LR::ActionType::Reduce, 12}},
               {"=", {LR::ActionType::Reduce, 12}},
               {">", {LR::ActionType::Reduce, 12}},
               {"{", {LR::ActionType::Reduce, 12}}},
              {}}},
            {83,
             {{{"!", {LR::ActionType::Reduce, 13}},
               {")", {LR::ActionType::Reduce, 13}},
               {"*", {LR::ActionType::Shift, 55}},
               {"+", {LR::ActionType::Reduce, 13}},
               {",", {LR::ActionType::Reduce, 13}},
               {"-", {LR::ActionType::Reduce, 13}},
               {"/", {LR::ActionType::Shift, 56}},
               {";", {LR::ActionType::Reduce, 13}},
               {"<", {LR::ActionType::Reduce, 13}},
               {"=", {LR::ActionType::Reduce, 13}},
               {">", {LR::ActionType::Reduce, 13}},
               {"{", {LR::ActionType::Reduce, 13}}},
              {}}},
            {84,
             {{{"!", {LR::ActionType::Reduce, 15}},
               {")", {LR::ActionType::Reduce, 15}},
               {"*", {LR::ActionType::Shift, 55}},
               {"+", {LR::ActionType::Reduce, 15}},
               {",", {LR::ActionType::Reduce, 15}},
               {"-", {LR::ActionType::Reduce, 15}},
               {"/", {LR::ActionType::Shift, 56}},
               {";", {LR::ActionType::Reduce, 15}},
               {"<", {LR::ActionType::Reduce, 15}},
               {"=", {LR::ActionType::Reduce, 15}},
               {">", {LR::ActionType::Reduce, 15}},
               {"{", {LR::ActionType::Reduce, 15}}},
              {}}},
            {85,
             {{{"else", {LR::ActionType::Shift, 87}},
               {"identifier", {LR::ActionType::Reduce, 28}},
               {"if", {LR::ActionType::Reduce, 28}},
               {"let", {LR::ActionType::Reduce, 28}},
               {"return", {LR::ActionType::Reduce, 28}},
               {"}", {LR::ActionType::Reduce, 28}}},
              {}}},
            {86,
             {{{"!", {LR::ActionType::Reduce, 17}},
               {")", {LR::ActionType::Reduce, 17}},
               {"*", {LR::ActionType::Reduce, 17}},
               {"+", {LR::ActionType::Reduce, 17}},
               {",", {LR::ActionType::Reduce, 17}},
               {"-", {LR::ActionType::Reduce, 17}},
               {"/", {LR::ActionType::Reduce, 17}},
               {";", {LR::ActionType::Reduce, 17}},
               {"<", {LR::ActionType::Reduce, 17}},
               {"=", {LR::ActionType::Reduce, 17}},
               {">", {LR::ActionType::Reduce, 17}},
               {"{", {LR::ActionType::Reduce, 17}}},
              {}}},
            {87, {{{"{", {LR::ActionType::Shift, 88}}}, {}}},
            {88,
             {{{"identifier", {LR::ActionType::Shift, 14}},
               {"if", {LR::ActionType::Shift, 19}},
               {"let", {LR::ActionType::Shift, 15}},
               {"return", {LR::ActionType::Shift, 20}}},
              {{"<assignment>", 21},
               {"<body>", 89},
               {"<function_call>", 22},
               {"<if>", 23},
               {"<return>", 24},
               {"<statement>", 16}}}},
            {89, {{{"}", {LR::ActionType::Shift, 90}}}, {}}},
            {90,
             {{{"identifier", {LR::ActionType::Reduce, 29}},
               {"if", {LR::ActionType::Reduce, 29}},
               {"let", {LR::ActionType::Reduce, 29}},
               {"return", {LR::ActionType::Reduce, 29}},
               {"}", {LR::ActionType::Reduce, 29}}},
              {}}}};

        CHECK_EQ(table, get_table());
    }

    TEST_CASE("[LRTests] factorial_parsing") {
        const CFG cfg = CFG::parse_ebnf("test/res/input/EBNF2CFG.txt");
        LR lr(cfg);

        const auto parse_result = lr.parse(StreamReader("test/res/input/factorial.pai"));

        std::ifstream expected_file("test/res/expected/LRTests-factorial_parsing.txt");
        std::stringstream expected{};
        expected << expected_file.rdbuf();
        expected_file.close();

        // std::ofstream reset("test/res/expected/LRTests-factorial_parsing.txt");
        // reset << parse_result.second->getContent();
        // reset.close();

        CHECK(parse_result.success);
        CHECK(parse_result.tree.has_value());
        CHECK_EQ(expected.str(), parse_result.tree.value()->getContent());
    }

    TEST_CASE("[LRTests] error1") {
        const CFG cfg = CFG::parse_ebnf("res/grammar/paithon.gram");
        LR lr(cfg);

        const auto parse_result = lr.parse(StreamReader("test/res/input/Error1.pai"));

        CHECK(!parse_result.success);
        CHECK(parse_result.tree.has_value());
        CHECK(parse_result.errors.size() == 1);

        if (!parse_result.errors.empty()) {
            std::string errorMessage = parse_result.errors[0].message;
            CHECK_EQ(errorMessage, "unexpected token found: `ain`");
        }
    }
    TEST_CASE("[LRTests] error2") {
        const CFG cfg = CFG::parse_ebnf("res/grammar/paithon.gram");
        LR lr(cfg);

        const auto parse_result = lr.parse(StreamReader("test/res/input/Error2.pai"));

        CHECK(!parse_result.success);
        CHECK(parse_result.tree.has_value());
        CHECK(parse_result.errors.size() == 1);

        if (!parse_result.errors.empty()) {
            std::string errorMessage = parse_result.errors[0].message;
            CHECK_EQ(errorMessage, "unexpected token found: `5`");
        }
    }
    TEST_CASE("[LRTests] error3") {
        const CFG cfg = CFG::parse_ebnf("res/grammar/paithon.gram");
        LR lr(cfg);

        const auto parse_result = lr.parse(StreamReader("test/res/input/Error3.pai"));

        CHECK(!parse_result.success);
        CHECK(parse_result.tree.has_value());
        CHECK(parse_result.errors.size() == 4);

        if (parse_result.errors.size() == 4) {
            CHECK_EQ(parse_result.errors[0].message, "unexpected token found: `{`");
            CHECK_EQ(parse_result.errors[1].message, "unexpected token found: `x`");
            CHECK_EQ(parse_result.errors[2].message, "unexpected token found: `}`");
            CHECK_EQ(parse_result.errors[3].message, "unexpected token found: `;`");
        }
    }

    TEST_CASE("[LRTests] error4") {
        const CFG cfg = CFG::parse_ebnf("res/grammar/paithon.gram");
        LR lr(cfg);

        const auto parse_result = lr.parse(StreamReader("test/res/input/Error4.pai"));

        CHECK(!parse_result.success);
        CHECK(parse_result.tree.has_value());
        CHECK(parse_result.errors.size() == 4);

        if (parse_result.errors.size() == 4) {
            CHECK_EQ(parse_result.errors[0].message, "unexpected token found: `,`");
            CHECK_EQ(parse_result.errors[1].message, "unexpected token found: `,`");
            CHECK_EQ(parse_result.errors[2].message, "unexpected token found: `,`");
            CHECK_EQ(parse_result.errors[3].message, "unexpected token found: `=`");
        }
    }
}
